[time]
disabled = false

format = "\uf64f[ $time ]($style)"
time_format = "%r"

[jobs]
symbol = "\uf53e"
threshold = 4
disabled = false

[character]
symbol = "\ufb0c"
error_symbol = "\uf656"
use_symbol_for_status = true

[docker_context]
symbol = "\uf308 "
only_with_files = true
disabled = false

[aws]
symbol = "\uf52c "

[gcloud]
symbol = "\ue7b2 "
style = "bright-cyan"
format = "on [$symbol$project (\\($region\\))]($style) "

[kubernetes]
symbol = "\ufd31 "
style = "blue"
disabled = false

[kubernetes.context_aliases]
"arn:aws:eks:us-east-1:655141976367:cluster/20210106-1-18" = "hippo-dev.tools"
"k8s-655141976367-us-east-1-20191224.hippo-dev.tools" = "hippo-dev.tools.old"
"k8s-256675650074-us-west-2-20191225.hippo-stage.tools" = "hippo-stage.tools"
"k8s-379103739298-us-east-1-20191225.hippo.tools" = "hippo.tools"
"k8s-768100956458-us-east-2-20200109.hippo.partners" = "hippo.partners"

[git_commit]
tag_disabled = false

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[golang]
symbol = "\ue626 "

[dotnet]
symbol = "\ue77f "
